### ISSUE TITLE
ByteOrder::read_uint looks incorrect for big endian

### ISSUE THREAD

**Issue by tmandry** [BurntSushi/regex-automata#19]
This code doesn't look correct for big endian:

https://github.com/BurntSushi/regex-automata/blob/8deb0dba13b72a2234830e08c1e6de2a1189bc8c/src/byteorder.rs#L37-L41

It always copies the bytes to the beginning of the 8-byte array, but then interprets them as whatever endianness is being used.

The byteorder crate [copies bytes to the end for big endian](https://docs.rs/byteorder/1.4.3/src/byteorder/lib.rs.html#1999).

(This issue came up in [code review](https://fuchsia-review.googlesource.com/c/fuchsia/+/561225/comments/1774b428_cdf32332), not from hitting any actual bugs.)

**Comment by BurntSushi** [comment]
Thanks, this should be fixed in `regex-automata 0.3`.
