### ISSUE TITLE
Provide a proc-macro for simple statically-compiled regexes

### ISSUE THREAD

**Issue by jrose-signal** [BurntSushi/regex-automata#25]
Skipping the parsing and compilation steps and instead deserializing from a DFA can save a lot on code size, an explicit goal for this crate. As documented, `ucd-generate` can compile a regex completely ahead of time and output a Rust file that you then include in your build. But this is a pretty heavy process; for a simple regex, the compilation time can be low enough that a proc-macro suffices.

[I've done a minimal version of this in Signal's RingRTC library.](https://github.com/signalapp/ringrtc/blob/c2088473c5ec62724e8270bcce6081f769cf5b51/src/rust/regex-aot/src/lib.rs) It doesn't support everything I'd expect an official version to support, but in our relatively minimal use case it works quite well. (I can also see emitting a warning or something if the compilation takes a significant amount of time, suggesting to use ucd-generate instead.)

**Comment by BurntSushi** [comment]
I do generally think this is a good idea, but I think it's unlikely I'll work on this or maintain it in the short term future. My main priority is bringing this crate into the official regex repo.

**Comment by jrose-signal** [comment]
Fair enough. I'd be happy to fill it out for you at some point, but I wouldn't want to be the permanent maintainer, so I guess it's back on the shelf for now. :-)

**Comment by BurntSushi** [comment]
I still think this is an interesting idea, but would prefer to see it prototyped in another crate first.
