### ISSUE TITLE
add method for checking whether two DFA could both return true on any input

### ISSUE THREAD

**Issue by droundy** [BurntSushi/regex-automata#26]
I'm not sure what this method would be called, but I don't think it would be too hard, and could be useful.

**Comment by BurntSushi** [comment]
Are you talking about DFA equivalence? That's what it sounds like. To do it correctly, you also need to minimize the DFA, which is quite expensive.

I believe this can be implemented outside of this crate. If not, we could explore what APIs would be needed to make that possible.

I think that's the path I'd like to go for as of now. I'm not convinced it is _actually_ useful, so I'd want to see if being used in the real world first. My guess is that this is a rather big/complex addition, so I think I need to insist on a higher standard than "could" be useful. :-)

Happy to re-open this and revisit it after an implementation exists and a solid use case has been demonstrated.

**Comment by droundy** [comment]
I'm not thinking of DFA equivalence, but something more like overlap, to compute if there exist any strings that could match both DFAs.

**Comment by BurntSushi** [comment]
I think you're asking for something to build the intersection of two DFAs and then ask whether it has any reachable match states.

I think my comment above applies equally well to that as well.

**Comment by droundy** [comment]
Yes, that is what I'm asking.
